breaking_changes = true
issues = true
emoji = true

[[commit_types]]
name = "feat"
emoji = "âœ¨"
description = "A new feature."

[[commit_types]]
name = "fix"
emoji = "ğŸ›"
description = "A bug fix."

[[commit_types]]
name = "chore"
emoji = "ğŸ§¹"
description = "Non-code changes that don't modify src or test files."

[[commit_types]]
name = "docs"
emoji = "ğŸ“š"
description = "Changes to documentation."

[[commit_types]]
name = "style"
emoji = "ğŸ’„"
description = "Code changes related to style and format."

[[commit_types]]
name = "refactor"
emoji = "â™»ï¸"
description = "Code changes that neither fixes a bug nor adds a feature."

[[commit_types]]
name = "perf"
emoji = "âš¡"
description = "Code changes that improves performance."

[[commit_types]]
name = "test"
emoji = "âœ…"
description = "Additions or modifications to tests."

[[commit_types]]
name = "build"
emoji = "ğŸ“¦"
description = "Changes that affect the build system or external dependencies."

[[commit_types]]
name = "change"
emoji = "ğŸ’©"
description = "An opinionated, potentially breaking change."

[[commit_types]]
name = "ci"
emoji = "ğŸš€"
description = "Changes to CI configuration."

[[commit_types]]
name = "revert"
emoji = "âª"
description = "Reverts a previous commit."
